Web/Models/ErrorViewModel.cs
namespace Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web/ViewModels/AccountOwnerEntryViewModel.cs
namespace Web.ViewModels
{
    using Core;

    public class AccountOwnerEntryViewModel
    {
        public int Id { get; set; }

        public string Number { get; set; }

        public decimal Balance { get; set; }

        public LegalEntityTypes LegalEntityType { get; set; }

        public string OwnerName { get; set; }
    }
}

Web/Controllers/EditOwnerController.cs
namespace Web.Controllers
{
    using Core;

    using Microsoft.AspNetCore.Mvc;

    public class EditOwnerController : Controller
    {
        private readonly IAccountService _accountService;

        public EditOwnerController(IAccountService accountService)
        {
            _accountService = accountService;
        }

        public IActionResult Index()
        {
            _accountService.SwapAccounts();

            return RedirectToAction("Index", "Home");
        }
    }
}

Web/Controllers/HomeController.cs
namespace Web.Controllers
{
    using System.Linq;

    using Core;

    using Microsoft.AspNetCore.Mvc;

    using Web.ViewModels;

    public class HomeController : Controller
    {
        private readonly IAccountService _accountService;

        public HomeController(IAccountService accountService)
        {
            _accountService = accountService;
        }

        public IActionResult Index()
        {
            var accounts = _accountService.GetAccounts();

            // here we can also to use mapping. I not include this to demo code, but you may check in class Map.cs to get an idea
            var result = accounts.Select(
                t =>
                    {
                        if (t.LegalEntity != null)
                        {
                            return new AccountOwnerEntryViewModel
                                       {
                                           Id = t.Id,
                                           Balance = t.Balance,
                                           Number = t.Number,
                                           OwnerName = t.LegalEntity.Name,
                                           LegalEntityType = t.LegalEntity.LegalEntityType
                                       };
                        }

                        return new AccountOwnerEntryViewModel
                                   {
                                       Id = t.Id,
                                       Balance = t.Balance,
                                       Number = t.Number,
                                       OwnerName = $"{t.Person.Surname} {t.Person.Name}",
                                       LegalEntityType = LegalEntityTypes.Person
                                   };
                    });

            return View(result);
        }
    }
}

Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@using Web.ViewModels
@model IEnumerable<Web.ViewModels.AccountOwnerEntryViewModel>

<div class="row">
        <h2>Accounts</h2>
        
        <table class="table">
            <thead>
            <tr>
                <th>
                    Number
                </th>
                <th>
                    Balance
                </th>
                <th>
                    Type of entity(person)
                </th>
                <th>
                    Owner
                </th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Number)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Balance)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LegalEntityType)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OwnerName)
                    </td>
                </tr>
            }
            </tbody>
        </table>
        
        <div>@Html.ActionLink("Change", "Index", "EditOwner")</div>
    </div>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DEMO</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Demo</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Demo</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>